### ISSUE TITLE
Communication issues between search-component and visitor-page-component

### ISSUE THREAD

**Issue by CaTwoPlus** [CaTwoPlus/net-core-angular-store#23]
Affected functionalities: 
- when using the search bar more than once no subsequent network requests are made.
- while displaying search results, no network requests are made for searching by categories. 

Issue only seem to affect touch screen devices / Chrome when device toolbar is toggled.

**Comment by CaTwoPlus** [comment]
Found the source of the problem, 
```
if (window.innerWidth < 680) {
            if (this.filterMenu) {
              this.renderer.addClass(this.filterMenu[0], '.dropdown-menu-sm-start');
            }
            if (this.orderMenu) {
              this.renderer.addClass(this.orderMenu[0], '.dropdown-menu-sm-start');
            }
          }
```
causes an error "ERROR TypeError: Cannot read properties of undefined (reading 'classList')
    at EmulatedEncapsulationDomRenderer2.addClass (platform-browser.mjs:619:12)
    at BaseAnimationRenderer.addClass (animations.mjs:276:23)
    at visitor-page.component.ts:108:29
    at source.subscribe.isComplete (switchMap.js:14:23)
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    at combineLatest.js:42:40
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    at subscribe.innerComplete (mergeInternals.js:25:28)", which stopped some click events from working.
